#! /bin/sh

perWindowLayoutD &
sxhkd &
xsetroot -cursor_name left_ptr &
~/.config/bspwm/scripts/set_wallpaper.py &
notify-send.py "brightness notification" --replaces-process brightness_ctl -t 1 &
notify-send.py "volume notification" --replaces-process volume_ctl -t 1 &
if [ $HOSTNAME = "yusufs-lenovo" ]; then
    motion -b -c ~/.config/motion/motion.conf &
fi
~/.config/bspwm/bar/start_lemonbar.py &

# polybar mybar &

bspc monitor -d -d 1 2 3 4 5 6 7 8 9 10

bspc config remove_unplugged_monitors true
bspc config removal_adjustment false

bspc config border_width     2
bspc config window_gap        8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme spiral

# colors
bspc config normal_border_color   "#44475a"
bspc config active_border_color   "#bd93f9"
bspc config focused_border_color  "#ff79c6"
bspc config presel_feedback_color "#6272a4"

wmname LG3D &

bspc config focus_follows_pointer true
bspc config external_rules_command "$(which external_rules)"
# bspc config pointer_follows_focus true

bspc rule -a Screenkey manage=off

~/.config/bspwm/scripts/swallow.py &
~/.config/bspwm/scripts/automatic_tab.py &
~/.config/bspwm/scripts/leave_empty_desk.py &
