name:                myXmonad
version:             0.1.0.0
homepage:            https://github.com/mono-cell
author:              mono-cell
maintainer:          jmk4929@gmail.com

dependencies:
  - base >= 4.7 && < 5
  - xmonad
  - xmonad-contrib
  - containers
  - text
  - X11
  - ghc

executables:
  xmonad:
    source-dirs:      src
    main:             main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
